site_name: Quadro
site_description: Your task board in markdown
site_author: Quadro Contributors
repo_url: https://github.com/morais90/quadro
repo_name: morais90/quadro

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo_dark_transparent.svg
  palette:
    # Dark mode (default)
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

extra_css:
  - stylesheets/quadro.css
  - stylesheets/home.css

extra_javascript:
  - javascripts/home-navigation.js

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            heading_level: 2
            show_signature_annotations: true
            separate_signature: true
            show_signature: true
            signature_crossrefs: true
            docstring_section_style: spacy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Why Quadro: getting-started/why-quadro.md
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
    - Core Concepts: getting-started/core-concepts.md
    - Milestones: getting-started/milestones.md
  - MCP Integration: mcp.md
  - CLI Reference: cli.md
